### ISSUE TITLE
File  /file.rml.ttl not found. Error

### ISSUE THREAD

**Issue by maartyman** [MaximeJakubowski/SRR#2]
I'm getting a "File /file.rml.ttl not found." that is originating from: https://github.com/MaximeJakubowski/SRR/blob/74d4faf7a268a5ac5371db52383f64e0371cbca5/src/main/java/App.java#L62 but the file actually exists. Can you print out the exception or not catch the exception so I know what is failing?

**Comment by MaximeJakubowski** [comment]
Yes, I need to refine the error handling on parse errors. I made a commit that changes this to printing a stack trace.
